@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "steve2",
  "password": "qwerty",
  "email": "marjorie.batz1@ethereal.email",
  "avatarColor": "blue",
  "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0gAAAMyAQMAAABtkHM/AAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAAFiS0dEAf8CLd4AAABrSURBVBgZ7cGBAAAAAMOg+1NP4AjVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjgBSwwABwrL8wAAAAABJRU5ErkJggg=="
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "steve",
  "password": "qwerty"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "nathaniel50@ethereal.email"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/7a71fb4905b168cc9697774707baf043c99a5eb7
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "qwerty1",
  "confirmPassword": "qwerty1"
}

