@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comments/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/<postId>/<commentId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "64df205a6d642e01669ac32e",
  "postId": "64df20836d642e01669ac335",
  "comment": "This is my first comment on steve 2",
  "profilePicture": "https://cdn.pixabay.com/photo/2023/08/11/06/02/bride-8182890_1280.jpg"
}
