@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "Nice one people",
  "bgColor": "#ffffff",
  "privacy": "Public",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dyamr9ym3/image/upload/v1659189696/62e539c0d8b514f6e42e3b5b",
  "feelings": "happy"
}

###
POST {{baseUrl}}/{{urlPath}}/post/image/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "Post with image created",
  "bgColor": "#4aa1f3",
  "privacy": "Public",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dyamr9ym3/image/upload/v1659189696/62e539c0d8b514f6e42e3b5b",
  "feelings": "",
  "image": ""
}

###
GET {{baseUrl}}/{{urlPath}}/post/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/images/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/post/648577f7623de4e745c46db2
Content-Type: application/json
Accept: application/json
withCredentials: true


###
PUT {{baseUrl}}/{{urlPath}}/post/64857b65426736bed76b54b4
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "Test",
  "bgColor": "red",
  "privacy": "public",
  "gifUrl": "",
  "profilePicture": "",
  "feelings": "sad"
}

###
PUT {{baseUrl}}/{{urlPath}}/post/image/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "",
  "bgColor": "",
  "privacy": "",
  "gifUrl": "",
  "profilePicture": "<cloudinary-user-profile-picture-url>",
  "feelings": "",
  "imgId": "<imgId-form-post>",
  "imgVersion": "<imgVersion-for-post>",
  "image": "<base64-encoded-string>"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/<postId>
Content-Type: application/json
Accept: application/json
withCredentials: true
